### ISSUE TITLE
video controls too small on fullscreen

### ISSUE THREAD

**Issue by lduboeuf** [mateosalta/cuddly-bassoon#13]
on N5 the control buttons ( toggle size or timeline ) are quite small and hard to touch

![screenshot20200704_212054179](https://user-images.githubusercontent.com/11663835/86521654-dbf43880-be53-11ea-87b4-bfca8401c006.png)

**Comment by lduboeuf** [comment]
this is not the case pn BQ4.5 but maybe related to last qtwebengine update ( devel)

**Comment by mateosalta** [comment]
I think the e4.5 doesn't have a high dpi screen, so it's 1x scale is the same scale as normal. this was a hack to make drop down's work(unfortunately it broke video scale, so it had to be 1x scale for fullscreen video) , I am soon going to use your patch.

**Comment by lduboeuf** [comment]
on N5 devel:
![screenshot20201015_233938898](https://user-images.githubusercontent.com/11663835/96189181-5139d400-0f40-11eb-8afe-4e3ce745e135.png)

![screenshot20201015_233955464](https://user-images.githubusercontent.com/11663835/96189251-70d0fc80-0f40-11eb-98d4-3603e940472f.png)

**Comment by lduboeuf** [comment]
fixed by #18
