### ISSUE TITLE
Opening YouTube links from Teleports doesn't bring up the video page

### ISSUE THREAD

**Issue by zubozrout** [mateosalta/cuddly-bassoon#14]
Hi,
I am not sure if this is a common issue or something unique to my device, os version or to my workflow, but I am unable to open YouTube links through Teleports on my Meizu MX4 (arale) with UT devel.

When I click on a YouTube link in Teleports your app is opened but instead of it then loading the respective video the app stays on the YouTube homepage.

Is that reproducible on your end?
Thank you.

**Comment by lduboeuf** [comment]
yes seems the case the first time when the app is not already launched

**Comment by zubozrout** [comment]
I didn't know, but can confirm that too @lduboeuf, thank you.

**Comment by mateosalta** [comment]
in order to launch first time, we need some kind of c++ handler

**Comment by lduboeuf** [comment]
Isn't it doable with the Arguments qml Type ?
like for calendar ? https://gitlab.com/ubports/apps/calendar-app/-/blob/master/qml/calendar.qml#L67

**Comment by zubozrout** [comment]
Which part of the code (probably in the Main.qml) is responsible for YouTube video to open in the first place (in case the app is already running)? Or is it something Morph does automatically?

Additionally, what makes the YouTube app associated with YouTube links?

Thank you.

**Comment by mateosalta** [comment]
I'm not sure this repo has the url part, hm... let me see

**Comment by mateosalta** [comment]
ah yes, i'm using more on the one in the store

So we need a .url-dispatcher file: 


`[
        {
                "protocol": "http",
                "domain-suffix": "youtube.com"
        },
        {
                "protocol": "https",
                "domain-suffix": "youtube.com"
        },
        {
                "protocol": "http",
                "domain-suffix": "m.youtube.com"
        },
        {
                "protocol": "https",
                "domain-suffix": "m.youtube.com"
        },
         {
                "protocol": "http",
                "domain-suffix": "youtu.be"
        },
        {
                "protocol": "https",
                "domain-suffix": "youtu.be"
        }
]'

this is noted in the hooks on the manifest:             "urls": "youtube-morphc.url-dispatcher"

in the connections section of main.qml you then put (this is the one that only works when already open):

`Connections {
        target: UriHandler
        onOpened: {
            webview.url = uris[0];


        }
    }`

for on open we need to try the arguments in the desktop file, the exec line you add %U, and then we have c++ file that has a way to pass the argument to qml something like this?         viewer.rootContext()->setContextProperty("url", app.arguments().at(1));


Then maybe use the code you had from the calendar

**Comment by mateosalta** [comment]
probally a good thing was left from this repo, as I have seen some people copy without modifying certain things ( like screensaver and permissions, and userscript) we don't want so many webapps trying to open youtube links...

**Comment by lduboeuf** [comment]
fixed by #18

**Comment by mateosalta** [comment]
also if we are making another twitter webapp - there was a option within the webappcontainer to make sure the shortnened links are taken care of so that t.co can resolve then send the real url to the url dispatcher, remind me to look into if anyone wants to tackle that problem
