### ISSUE TITLE
can't stay connected 

### ISSUE THREAD

**Issue by lduboeuf** [mateosalta/cuddly-bassoon#15]
on devel,  i need to authenticate each time.

**Comment by mateosalta** [comment]
I think this is a problem with dev, I just had the same problem with telegram web

**Comment by lduboeuf** [comment]
yes it seems to. The same for gmail webapp

**Comment by lduboeuf** [comment]
follow up here: https://github.com/ubports/morph-browser/issues/347

**Comment by lduboeuf** [comment]
closed by ubports/morph-browser#347
