### ISSUE TITLE
video in fullscreen is truncated

### ISSUE THREAD

**Issue by lduboeuf** [mateosalta/cuddly-bassoon#17]
on N5 devel

![screenshot20201015_235427505](https://user-images.githubusercontent.com/11663835/96190091-edb0a600-0f41-11eb-92cc-e455b87248de.png)

**Comment by lduboeuf** [comment]
can't reproduce on BQ4.5 RC

**Comment by mateosalta** [comment]
ah, I think the bq has a screen scaling of 1, I think this bug appears on devices that have a higher scale. probably the reason for the zoom "quick fix" I had on the version in the store - although this presents a different unique problem with the small scale in controls in full-screen. I think we can go back to not using zoom and just using the scaling flag in qmlscene

**Comment by lduboeuf** [comment]
fixed by https://github.com/mateosalta/cuddly-bassoon/pull/18 and at lower level
