### ISSUE TITLE
Drains battery life fast when watching videos on any resolution (Nexus 5)

### ISSUE THREAD

**Issue by ssabz** [mateosalta/cuddly-bassoon#4]
I'm not sure if it's a OS issue or an App issue, but whenever I watch videos the battery drains really fast at any resolution.

Device: Nexus 5
OS version: OTA-8

**Comment by mateosalta** [comment]
its a problem with the browser/container, since qtwebengine is not hardware accelerated it uses software rendering and uses the cpu
