### ISSUE TITLE
Add way to change video resolution

### ISSUE THREAD

**Issue by JulianGro** [mateosalta/cuddly-bassoon#5]
There isn't any obvious way to change the resolution of a video.
On a tablet, this is pretty important, since 360p looks like absolute trash; Especially in fullscreen.

I would guess that this might be a limitation of the web container you are using. It would be nice if you could redirect the issue to the container if that is actually not capable.

**Comment by mateosalta** [comment]
i think it is how the browser sends the video to mobile site, try the new youtube that has a dark background since it uses the desktop user agent

**Comment by mateosalta** [comment]
I think it was added, and the morph dropdown menus make this easier
