### ISSUE TITLE
Asking permission

### ISSUE THREAD

**Issue by symbuzzer** [mateosalta/cuddly-bassoon#55]
Hello. First of all, thank you very much for your beautiful work.

If you allow, I would like to develop my own applications using this project as a template and share them on the open store.

All of these applications will be free, open source and ad-free. There may be advertisements, paid memberships, etc. only on some websites that the application will run.

I would like to give credit and thank you to both your github profile and this project in the readme.md file in the github repository of these applications.

Is this suitable for you?

**Comment by lduboeuf** [comment]
Hello @symbuzzer ,

I'm not the maintainer of this webapp, but there is no intellectual property, this webapp just use shared components and its GPL so here to be used/shared

**Comment by symbuzzer** [comment]
Thanks again
