### ISSUE TITLE
Creating Youtube Music app

### ISSUE THREAD

**Issue by symbuzzer** [mateosalta/cuddly-bassoon#56]
Hi...
I made base this app and tried to build Youtube Music app. Bu it gives this error:
![photo1714913100](https://github.com/mateosalta/cuddly-bassoon/assets/9841184/a5194588-70b5-4636-892a-c489835c362e)

Here is changes I made: https://github.com/mateosalta/cuddly-bassoon/compare/main...symbuzzer:musiki:main
Can u help to find problem, please?
Thanks...

**Comment by Fuseteam** [comment]
Looks like you made a typo in youtube-music-web
Also as per license you aren't supposed to modify/remove the existing licensing you can however add your name below that of mateo
Finally github issues are not that suitable to provide help, feel free to join us on telegram at https://t.me/ubuntuappdeven

**Comment by symbuzzer** [comment]
> Looks like you made a typo in youtube-music-web 

On where? I double checked every file. 


> Also as per license you aren't supposed to modify/remove the existing licensing you can however add your name below that of mateo 

I am new on licences. What did I wrong?

> Finally github issues are not that suitable to provide help, feel free to join us on telegram at https://t.me/ubuntuappdeven

I will close it sir

**Comment by Fuseteam** [comment]
This is wrong https://github.com/mateosalta/cuddly-bassoon/commit/7c0ac4fd02cf04a76dc727cbf0759948af4287da

**Comment by symbuzzer** [comment]
> This is wrong [7c0ac4f](https://github.com/mateosalta/cuddly-bassoon/commit/7c0ac4fd02cf04a76dc727cbf0759948af4287da)

already has LICENSE.ms file with same license

**Comment by Fuseteam** [comment]
If it is the same license then it is fine.

As you are being helped in the appdev grouo about the rest, i'll close this issue
