### ISSUE TITLE
Scaling too big, thumbnails pixelated on E4.5

### ISSUE THREAD

**Issue by PeterNerlich** [mateosalta/cuddly-bassoon#9]
Before 2.3.6 this was ideal for the E4.5, I guess it differs from device to device.

![screenshot20200315_112716987](https://user-images.githubusercontent.com/10530729/76699732-ae229280-66b0-11ea-9c03-550a2d5a2739.png)
![screenshot20200315_112735142](https://user-images.githubusercontent.com/10530729/76699733-afec5600-66b0-11ea-8771-acfce3ebf44f.png)

**Comment by lduboeuf** [comment]
i think it is fixed now
